version: '3.8'
services:
  web:
    build: .
    # 8086:80 -> HTTP (Mevcut port)
    # 2222:22 -> SSH (Yeni port)
    ports:
      - "8096:80"
      - "2232:22"
    volumes:
      - /home/umbrel/web/www/:/var/www/html/


    restart: always
