version: '3.8'
services:
  web:
    build: .
    ports:
      # HTTP host portu artık HOST_HTTP_PORT değişkeninden okunur
      - "${HOST_HTTP_PORT}:80"
      # SSH host portu artık HOST_SSH_PORT değişkeninden okunur
      - "${HOST_SSH_PORT}:22"
    volumes:
      # Volume yolu için önceki gibi proje adını kullanmaya devam ediyoruz
      - /home/umbrel/web/${COMPOSE_PROJECT_NAME}/www/:/var/www/html/

    restart: always
